[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.172"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
lto = true
panic = 'abort'
strip = true
codegen-units = 1
